kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: platformsupporttemplates.argoproj.io  # Corrected to match spec.names.plural + "." + spec.group
spec:
  group: argoproj.io
  scope: Namespaced  # Added scope
  names:
    kind: PlatformSupportTemplate  # Added kind
    listKind: PlatformSupportTemplateList  # Added listKind
    plural: platformsupporttemplates  # Added plural
    singular: platformsupporttemplate  # Added singular
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object  # Added type for spec
            # Add specific properties for ArgoSupportTemplate here
