apiVersion: genai.argoproj.io/v1alpha1
kind: AIArgoSupportRun
metadata:
  name: YYYYMMDDHHMMSS
  namespace: testns2
  labels:
    app: istio-host-split
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: myapp
spec:
refreshInterval: 1m
  genos:
  - url: http://genos.intuit.com
    headers:
    - name: appid
      valueFrom:
        secretKeyRef
      key: app.id
  tokenBuilder:
    resourceAggregators:
    -kind: rollout
      status: {{.status}}
    - kind: pod
      count: 1
      status: {{.status}}
      containerStatus
      - ready: false
      logProcessor:
      - type: error
      - primary: default
      - secondary // not in scope
    - events:
    filters
    - type: error
    namespace: .metadata.namespace
    feedbackCollected: false
status: