kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: argosupportruns.genai.argoproj.io
spec:
  group: genai.argoproj.io
  scope: Namespaced  # Assuming namespaced resources
  names:
    kind: ArgoSupportRun
    listKind: ArgoSupportRunList
    plural: argosupportruns
    singular: argosupportrun
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        # Add specific properties for your ArgoSupportRun resource here
        # Based on the provided YAML, some potential properties include:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            # ... properties for spec section from your previous attempts ...
          # Status section definition (replace with your desired status properties)
          status:
            type: object
            properties:
              # Define properties for the status section based on your use case
              # Example:
              lastUpdated:
                type: string
                format: date-time
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    message:
                      type: string
                    # Add additional properties as needed
