apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: argosupporttemplates.argoproj.io
spec:
  group: argoproj.io
  scope: Namespaced  # Assuming namespaced resources
  names:
    kind: ArgoSupportTemplate
    listKind: ArgoSupportTemplateList
    plural: argosupporttemplates
    singular: argosupporttemplate
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object  # Spec section is schemaless
            x-kubernetes-preserve-unknown-fields: true  # Allow unknown fields

