apiVersion: argoproj.io/v1alpha1
kind: ArgoOperationResult
metadata:
  creationTimestamp: '2024-03-08T20:47:23Z'
  generation: 1
  labels:
    app.kubernetes.io/instance: test2
  name: genai-analysis-result
  namespace: testns2
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ArgoOperationTemplate
    name: genai-analysis
    uid: 3f220955-db20-422c-b1d0-71772bd50618
spec:
  args:
    - name: service-name
  operations:
     - plugin:
        argoproj/curl:
          url: https://example.com/
          some_key: some_value
     - name: gen-analysis
       args:
        - name: phase
          value: degraded
        - name: inlinePrompt
          value: "Analyze condition or status conditions that are not phase ready"
       feedback: false
       externalProvider: 
        url: http://genos.intuit.com
        headers:
        - name: appid
          valueFrom:
            secretKeyRef:
              name: my-genos-secret  # Reference to the Secret containing appid
              key: app.id
        timeout: 30s
        retry: 3
status: 
  startedAt: '2024-02-27T18:10:23Z'
  finishedAt: '2024-02-27T18:11:03Z'
  phase: completed
  message: "Operation finished Terminated"
  OperationResults:
    - name: genai-analysis
      finishedAt: '2024-03-12T18:26:03Z'
      startedAt: '2024-03-12T18:26:03Z'
      summary: {}
      feedback:
      - ispositive: true
        notes: "nice"
        finishedAt: '2024-02-27T18:11:03Z'
      help:
        stackOverflow:
        - link1:  # Empty value
        - link2:  # Empty value
        slack:
          primary: #msaas-support
          secondary: #msaas-support
 