apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: argooperationtemplates.argoproj.io
spec:
  group: argoproj.io
  scope: Namespaced  # Assuming namespaced resources
  names:
    kind: ArgoOperationTemplate
    listKind: ArgoOperationTemplateList
    plural: argooperationtemplates
    singular: argooperationtemplate
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object  
            x-kubernetes-preserve-unknown-fields: true 

