apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-host-split
  name: istio-host-split-canary

spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: istio-host-split
---
apiVersion: v1
kind: Service
metadata:
  name: istio-host-split-stable

spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: istio-host-split
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate

spec:
  args:
  - name: service-name
  metrics:
  - count: 4
    failureLimit: 1
    interval: 30s
    name: success-rate
    provider:
      prometheus:
        address: http://prometheus-k8s.monitoring:9090
        query: "sum(irate(istio_requests_total{destination_service_name=~\"{{args.service-name}}\",response_code!~\"5.*\"}[1m]))
          \n/\nsum(irate(istio_requests_total{destination_service_name=~\"{{args.service-name}}\"}[1m]))"
    successCondition: result[0] >= 0.95
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: istio-host-split

spec:
  replicas: 4
  selector:
    matchLabels:
      app: istio-host-split
  strategy:
    canary:
      analysis:
        args:
        - name: service-name
          value: istio-host-split-canary
        startingStep: 3
        templates:
        - templateName: success-rate
      canaryService: istio-host-split-canary
      stableService: istio-host-split-stable
      steps:
      - setWeight: 25
      - pause: {}
      - setWeight: 35
      - pause:
          duration: 10s
      - setWeight: 50
      - pause:
          duration: 10s
      - setWeight: 75
      - pause:
          duration: 2m
      trafficRouting:
        istio:
          virtualService:
            name: istio-host-split-vsvc
            routes:
            - primary
  template:
    metadata:
      labels:
        app: istio-host-split
    spec:
      containers:
      - image: ghcr.io/argocon22workshop/rollouts-demo:green
        name: istio-host-split
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 16Mi
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-host-split-gateway

spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-host-split-vsvc

spec:
  gateways:
  - istio-host-split-gateway
  hosts:
  - '*'
  http:
  - name: primary
    route:
    - destination:
        host: istio-host-split-stable
      weight: 100
    - destination:
        host: istio-host-split-canary
      weight: 0
