apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - canary.yaml
  - analysis_template.yaml
  - ai_argosupport_template.yaml
 # - ai_argosupportrun.yaml

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

